export const config = {
  NEXT_PUBLIC_APPWRITE_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!,
  NEXT_PUBLIC_APPWRITE_PROJECT_KEY: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_KEY!,
  NEXT_PUBLIC_DATABASE_ID: process.env.NEXT_PUBLIC_DATABASE_ID!,
  NEXT_PUBLIC_TASK_COLLECTION_ID: process.env.NEXT_PUBLIC_TASK_COLLECTION_ID!,
  NEXT_PUBLIC_USERDATA_COLLECTION_ID: process.env.NEXT_PUBLIC_USERDATA_COLLECTION_ID!,
  NEXT_PUBLIC_BUCKET_ID: process.env.NEXT_PUBLIC_BUCKET_ID!,
};
